---
title: "Microbial Growth Curve Plots"
author: Douglas A. Campbell
---

Demonstration plots of microbial growth curves for examinations and assignments

```{r load libraries}
library(tidyverse)
```

```{r generate data}
PA0 <- 10
PAMax <- 200
PAmu <- log(2)
PAlag <- 2

PB0 <- 20
PBMax <- 500
PBmu <- log(2)
PBlag <- 4

GrowthData <- tibble(Day = c(0,1,2,3,4,5,6,7,8,9,10))

GrowthData <- GrowthData %>%
  mutate(PtA = (PAMax * (PA0*exp(Day*PAmu))) /(PAMax + (PA0 * (exp(PAmu * Day) - 1)))) %>%
  mutate(PtALag = if_else(Day < PAlag, PA0, (PAMax * (PA0*exp((Day-PAlag)*PAmu))) /(PAMax + (PA0 * (exp(PAmu * (Day-PAlag)) - 1))))) %>%
  mutate(PtB = (PBMax * (PB0*exp(Day*PBmu))) /(PBMax + (PB0 * (exp(PBmu * Day) - 1)))) %>%
  mutate(PtBLag = if_else(Day < PBlag, PB0, (PBMax * (PB0*exp((Day-PBlag)*PBmu))) /(PBMax + (PB0 * (exp(PBmu * (Day-PBlag)) - 1))))) |>
  mutate(DayVar = rnorm(n = length(Day), mean = Day, sd = Day *0.2),
    PtAVar = rnorm(n = length(PtA), mean = PtA, sd = PtA *0.2),
    PtBLagVar = rnorm(n = length(PtBLag), mean = PtBLag, sd = PtBLag *0.1))
```

```{r PtA plot}
GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = PtA)) +
  geom_line(aes(x = Day, y = PtA)) +
  scale_x_continuous(expand = c(0,0), limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(expand = c(0,0), limits = c(0,PAMax), breaks = seq(from=min(0),
              to=max(PAMax), by = 200)) + 
   theme_bw(base_size = 14)

ggsave(
  "PtAPlot.png",
  plot = last_plot(),
  path = file.path("Plots")
)

GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = log(PtA))) +
  #geom_smooth(aes(x = DayVar, y = log(PtA)), method = "lm") +
  #geom_smooth(data = subset(GrowthData, DayVar <= 4), aes(x = DayVar, y = log(PtA)), method = "lm") +
  scale_x_continuous(expand = c(0,0), limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(expand = c(0,0)) + 
  theme_bw(base_size = 14)

ggsave(
  "logPtAPlot.png",
  plot = last_plot(),
  path = file.path("Plots")
)

GrowthData %>%
  ggplot() +
  geom_point(aes(x = DayVar, y = PtAVar)) +
  geom_line(aes(x = DayVar, y = PtAVar)) +
  scale_x_continuous(expand = c(0,0), limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(expand = c(0,0)) + 
  theme_bw(base_size = 14)

ggsave(
  "PtAVarPlot.png",
  plot = last_plot(),
  path = file.path("Plots")
)

GrowthData %>%
  ggplot() +
  geom_point(aes(x = DayVar, y = log(PtAVar))) +
  #geom_smooth(aes(x = DayVar, y = log(PtAVar)), method = "lm") +
  scale_x_continuous(expand = c(0,0), limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(expand = c(0,0)) + 
  theme_bw(base_size = 14)

ggsave(
  "logPtAVarPlot.png",
  plot = last_plot(),
  path = file.path("Plots")
)
```



```{r PtALag plot}
GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = PtALag)) +
  geom_line(aes(x = Day, y = PtALag)) +
  scale_x_continuous(limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(limits = c(0,PAMax), breaks = seq(from=min(0),
              to=max(PAMax), by = 100)) + 
  theme_bw()

```


```{r PtB plot}
GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = PtB)) +
  geom_line(aes(x = Day, y = PtB)) +
  scale_x_continuous(limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(limits = c(0,PBMax), breaks = seq(from=min(0),
              to=max(PBMax), by = 100)) + 
  theme_bw()

```

```{r PtBLag plot}
GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = PtBLag)) +
  geom_line(aes(x = Day, y = PtBLag)) +
  scale_x_continuous(limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(limits = c(0,PBMax), breaks = seq(from=min(0),
              to=max(PBMax), by = 100)) + 
  theme_bw()

```


```{r PtBLagVar plot}
GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = PtBLagVar)) +
  geom_line(aes(x = Day, y = PtBLagVar)) +
  scale_x_continuous(limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  scale_y_continuous(limits = c(0,PBMax), breaks = seq(from=min(0),
              to=max(PBMax), by = 100)) + 
  theme_bw()

ggsave(
  "PtBLagVarPlot.png",
  plot = last_plot(),
  path = file.path("Plots")
)

```


```{r PtBLagVar plot}
GrowthData %>%
  ggplot() +
  geom_point(aes(x = Day, y = log(PtBLagVar))) +
  geom_line(aes(x = Day, y = log(PtBLagVar))) +
  scale_x_continuous(limits = c(0,max(GrowthData$Day)), breaks = round(seq(0,10))) +
  #scale_y_continuous(limits = c(0,PBMax), breaks = seq(from=min(0),
             # to=max(PBMax), by = 100)) + 
  theme_bw()


ggsave(
  "logPtBVarPlot.png",
  plot = last_plot(),
  path = file.path("Plots")
)
```